from Bio.Data.CodonTable import CodonTable, standard_dna_table
from typing import NamedTuple


class Frames(NamedTuple):
    frame_h1: str
    frame_h2: str
    frame_h3: str
    frame_h4: str
    frame_l1: str
    frame_l2: str
    frame_l3: str
    frame_l4: str


supE_codon_table = CodonTable(
    forward_table={**standard_dna_table.forward_table, 'TAG': 'Q'},
    back_table=standard_dna_table.back_table,
    start_codons=standard_dna_table.start_codons,
    stop_codons=['TAA', 'TGA'],
)


seq_liab_db = [
    {'name': 'Glycosylation',
     'regex': 'N[^P][ST][^P]',
     'score': 3,
    },
    {'name': 'Isomerization',
     'regex': 'D[GSTDH]',
     'score': 3,
    },
    {'name': 'Fragmentation',
     'regex': 'D[PQ]',
     'score': 3,
    },
    {'name': 'Extra Cysteine',
     'regex': 'C',
     'score': 3,
    },
    {'name': 'Deamidation CDR (High)',
     'regex': 'N[GSAT]',
     'score': 2,
    },
    {'name': 'Hydrolysis',
     'regex': 'NP',
     'score': 2,
    },
    {'name': 'Cleavage',
     'regex': 'TS',
     'score': 2,
    },
    {'name': 'Deamidation CDR (Med)',
     'regex': 'NH',
     'score': 1,
    },
    {'name': 'Integrin binding aVb3',
     'regex': 'RGD|RYD|KGD|NGR',
     'score': 1,
    },
    {'name': 'Integrin binding a4b1',
     'regex': 'LDV',
     'score': 1,
    },
    {'name': 'Integrin binding a2b1',
     'regex': 'DGE',
     'score': 1,
    },
    {'name': 'CD11c/CD18 binding',
     'regex': 'GPR',
     'score': 1,
    },
    {'name': 'Hydrophobicity',
     'regex': '[WF][WF]',
     'score': 1,
    },
    {'name': 'Oxidation',
     'regex': 'M',
     'score': 0,
    },
    {'name': 'Deamidation CDR (Low)',
     'regex': '[STK]N',
     'score': 0,
    },
]


# Dict of FRs of all supported libraries
lib_frames = {
    'SH_VH3-23_Vk1-39':
        Frames(
            'GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGA',  # FRH1
            'TGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTC',  # FRH2
            'GACTCCGTGAAGGGCCGGTTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCCGTGTATTACTGT',  # FRH3
            'TGGGGCCAGGGCACCCTGGTCACCGTCTCCTCA',  # FRH4
            'GACATCCAGATGACCCAGTCTCCATCCTCCCTGTCTGCATCTGTAGGAGACCGTGTCACCATCACTTGCCGG',  # FRL1
            'TTAAATTGGTATCAGCAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTAT',  # FRL2
            'GGGGTCCCATCACGCTTCAGTGGCAGTGGATCTGGGACAGATTTCACTCTCACCATCAGCAGTCTGCAACCTGAAGATTTTGCAACTTACTACTGTCAA',  # FRL3
            'TTCGGCGGAGGTACCAAGGTGGAGATCAAA',  # FRL4
        ),
    'AI_VH3-23_Vk3-20':
        Frames(
            'GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCCTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGCGCAGCCTCTGGA',  # FRH1
            'TGGGTCCGCCAGGCTCCTGGGAAGGGGCTGGAGTGGGTC',  # FRH2
            'GACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAACTCCAAGAACACACTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGT',  # FRH3
            'TGGGGCCAAGGAACCCTGGTCACCGTCTCCTCA',  # FRH4
            'GAAATCGTGTTGACCCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGAGAAAGAGCCACCCTCTCCTGCAGG',  # FRL1
            'TTAGCCTGGTACCAACAGAAACCAGGGCAGGCCCCTAGGCTCCTGATCTAT',  # FRL2
            'GGGATCCCTGACAGGTTCAGTGGCAGTGGATCTGGGACAGATTTCACTCTCACCATCAGCAGTCTGGAGCCTGAAGATTTTGCAGTTTATTACTGTCAG',  # FRL3
            'TTTGGCCAAGGGACCAAGGTGGAGATCAAA'  # FRL4
        ),
    'AI_VH3-23_Vk1-39':
        Frames(
            'GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCCTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGCGCAGCCTCTGGA',  # FRH1
            'TGGGTCCGCCAGGCTCCTGGGAAGGGGCTGGAGTGGGTC',  # FRH2
            'GACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAACTCCAAGAACACACTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGT',  # FRH3
            'TGGGGCCAAGGAACCCTGGTCACCGTCTCCTCA',  # FRH4
            'GACATCCAGATGACCCAGTCTCCATCCTCCCTGTCTGCATCTGTAGGAGACAGAGTCACCATCACTTGCAGG',  # FRL1
            'TTAAACTGGTACCAACAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTAT',  # FRL2
            'GGGGTCCCTTCAAGGTTCAGTGGCAGTGGATCTGGGACAGATTTCACTCTCACCATCAGCAGTCTGCAGCCTGAAGATTTTGCAACTTATTACTGTCAA',  # FRL3
            'TTTGGCCAAGGGACCAAGGTGGAGATCAAA'  # FRL4
        ),
    'AI_VH1-69_Vk3-20':
        Frames(
            'CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGTCCTCCGTGAAGGTCTCCTGCAAGGCCTCTGGA',  # FRH1
            'TGGGTCCGCCAGGCTCCTGGGCAAGGGCTGGAGTGGATG',  # FRH2
            'CAGAAGTTCCAGGGCCGAGTCACCATCACCGCCGACGAATCCACGAGCACAGCCTATATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCTGTGTATTACTGT',  # FRH3
            'TGGGGCCAAGGAACCCTGGTCACCGTCTCCTCA',  # FRH4
            'GAAATCGTGTTGACCCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGAGAAAGAGCCACCCTCTCCTGCAGG',  # FRL1
            'TTAGCCTGGTACCAACAGAAACCAGGGCAGGCCCCTAGGCTCCTGATCTAT',  # FRL2
            'GGGATCCCTGACAGGTTCAGTGGCAGTGGATCTGGGACAGATTTCACTCTCACCATCAGCAGTCTGGAGCCTGAAGATTTTGCAGTTTATTACTGTCAA',  # FRL3
            'TTCGGCCAAGGGACCAAGGTGGAGATCAAA'  # FRL4
        ),
    'AI_VH1-69_Vk1-39':
        Frames(
            'CAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGTCCTCCGTGAAGGTCTCCTGCAAGGCCTCTGGA',  # FRH1
            'TGGGTCCGCCAGGCTCCTGGGCAAGGGCTGGAGTGGATG',  # FRH2
            'CAGAAGTTCCAGGGCCGAGTCACCATCACCGCCGACGAATCCACGAGCACAGCCTATATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCTGTGTATTACTGT',  # FRH3
            'TGGGGCCAAGGAACCCTGGTCACCGTCTCCTCA',  # FRH4
            'GACATCCAGATGACCCAGTCTCCATCCTCCCTGTCTGCATCTGTAGGAGACAGAGTCACCATCACTTGCAGG',  # FRL1
            'TTAAACTGGTACCAACAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTAT',  # FRL2
            'GGGGTCCCTTCAAGGTTCAGTGGCAGTGGATCTGGGACAGATTTCACTCTCACCATCAGCAGTCTGCAGCCTGAAGATTTTGCAACTTATTACTGTCAA',  # FRL3
            'TTTGGCCAAGGGACCAAGGTGGAGATCAAA'  # FRL4
        ),
    'PureLibra':
        Frames(
            'GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCT',  # FRH1
            'GCCATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTGTCAGCT',  # FRH2
            'TACTACGCAGACTCCGTGAAGGGCCGGTTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCCGTATATTACTGTGCG',  # FRH3
            'TGGGGCCAGGGAACCCTGGTCACCGTGTCCTCA',  # FRH4
            'ACGGAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGT',  # FRL1
            'CTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTAT',  # FRL2
            'AGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGT',  # FRL3
            'TTTGGCCAGGGGACCAAGCTGGAGATCAAACGAGC'  # FRL4
        )
    }
